# Generated by Django 3.0.6 on 2020-06-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thongtin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=100)),
                ('msv', models.CharField(max_length=30)),
                ('lop', models.CharField(max_length=10)),
                ('quequan', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='lichhoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenmonhoc', models.CharField(max_length=100)),
                ('tghoc', models.CharField(max_length=100)),
                ('phonghoc', models.CharField(max_length=10)),
                ('hoten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sinhvien.thongtin')),
            ],
        ),
        migrations.CreateModel(
            name='ketqua_ht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenmonhoc', models.CharField(max_length=100)),
                ('sotinchhi', models.IntegerField()),
                ('diem', models.IntegerField()),
                ('hoten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sinhvien.thongtin')),
            ],
        ),
    ]
