# Generated by Django 3.0.6 on 2020-06-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sinhvien', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lichhoc',
            options={'default_related_name': 'app_sinhvien'},
        ),
        migrations.AlterField(
            model_name='ketqua_ht',
            name='hoten',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='hoten',
            field=models.CharField(max_length=100),
        ),
    ]
